---
name: Channels DVR Server
version: "1.0.19"
slug: channels-dvr
description: Manage and record live TV with Channels DVR Server
url: https://github.com/mekenthompson/hassio-addons
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
host_network: true
webui: http://[HOST]:[PORT:8089]
ports:
  8089/tcp: 8089
map:
  - share:rw
  - media:rw
hassio_api: true
options: {}
schema: {}

